# Generated by Django 5.1.4 on 2025-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaquecolor',
            name='name',
            field=models.CharField(choices=[('#000000', 'Black'), ('#FFFFFF', 'White'), ('#FF5733', 'Red'), ('#33FF57', 'Green')], default='#000000', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='textcolor',
            name='name',
            field=models.CharField(choices=[('#000000', 'Black'), ('#FFFFFF', 'White'), ('#FF5733', 'Red'), ('#33FF57', 'Green')], default='#000000', max_length=100),
        ),
    ]
