# Generated by Django 5.1.4 on 2025-03-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_activity_fixed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='lignetexte',
            name='position_y',
            field=models.IntegerField(default=45),
        ),
    ]
