# Generated by Django 5.1.4 on 2025-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plaquecustomization_text_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_first_vu',
            field=models.BooleanField(default=False),
        ),
    ]
