# Generated by Django 5.1.4 on 2025-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(),
        ),
    ]
