# Generated by Django 5.1.4 on 2025-03-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_thickness_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedproduct',
            name='jpeg_field',
            field=models.FileField(blank=True, null=True, upload_to='custom_jpegs/'),
        ),
        migrations.AddField(
            model_name='customizedproduct',
            name='pdf_field',
            field=models.FileField(blank=True, null=True, upload_to='custom_pdfs/'),
        ),
    ]
