# Generated by Django 5.1.4 on 2025-02-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_activity_image_category_image_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
