# Generated by Django 5.1.4 on 2025-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_activity_alt_text_category_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
