# Generated by Django 5.1.4 on 2025-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_material_alt_text_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_6',
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_lines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_styles',
            field=models.JSONField(default=list),
        ),
    ]
