# Generated by Django 5.1.4 on 2025-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_example_text_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='example_text_lines',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_styles',
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_line_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_line_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_line_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='example_text_line_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
