# Generated by Django 5.1.4 on 2025-02-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_example_text_lines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('fichier', models.FileField(upload_to='polices/')),
            ],
        ),
        migrations.CreateModel(
            name='StyleTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gras', models.BooleanField(default=False)),
                ('italique', models.BooleanField(default=False)),
                ('souligne', models.BooleanField(default=False)),
                ('couleur', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='example_text_line_6',
        ),
        migrations.CreateModel(
            name='LigneTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True)),
                ('taille_police', models.PositiveIntegerField(default=14)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('plaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.product')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.police')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.styletexte')),
            ],
        ),
    ]
