# Generated by Django 5.1.4 on 2025-02-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_police_styletexte_remove_product_example_text_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignetexte',
            old_name='plaque',
            new_name='product',
        ),
    ]
