# Generated by Django 5.1.4 on 2025-02-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_logo_height_product_logo_position_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='fichier',
        ),
    ]
