# Generated by Django 5.1.4 on 2025-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_police_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignetexte',
            name='texte',
            field=models.CharField(max_length=100),
        ),
    ]
