# Generated by Django 5.1.4 on 2025-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
        migrations.AddField(
            model_name='product',
            name='qrCode_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qrCode_position_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qrCode_position_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qrCode_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
