# Generated by Django 5.1.4 on 2025-03-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customizedstyletexte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedlignetexte',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customizedstyletexte'),
        ),
    ]
